#define DEFAULT_CONFIGURATION_FILE "/etc/dlt-system.conf"

#define DEFAULT_APPLICATION_ID "SYS"

#define DEFAULT_SYSLOG_CONTEXT_ID "SYSL"

#define DEFAULT_SYSLOG_PORT 47111

#define DEFAULT_KERNEL_VERSION_MODE 1
#define DEFAULT_KERNEL_VERSION_CONTEXT_ID "VERS"
