#define DEFAULT_CONFIGURATION_FILE "/etc/dlt-system.conf"
#define DEFAULT_APPLICATION_ID "SYS"

#define DEFAULT_SYSLOG_CONTEXT_ID "SYSL"
#define DEFAULT_SYSLOG_PORT 47111

#define DEFAULT_FILETRANSFER_DIRECTORY "/tmp/filetransfer"
#define DEFAULT_FILETRANSFER_CONTEXT_ID "FILE"
#define DEFAULT_FILETRANSFER_TIME_STARTUP 30
#define DEFAULT_FILETRANSFER_TIME_DELAY	10

#define DEFAULT_LOG_PROCESSES_MODE 0
#define DEFAULT_LOG_PROCESSES_CONTEXT_ID "PROC"
