/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#ifndef __DLT_VERSION_H_
#define __DLT_VERSION_H_

#define _DLT_PACKAGE_VERSION_STATE "@PRINT_VERSION_STATE@"
#define _DLT_PACKAGE_VERSION "@PRINT_VERSION@"
#define _DLT_PACKAGE_MAJOR_VERSION "@PRINT_MAJOR_VERSION@"
#define _DLT_PACKAGE_MINOR_VERSION "@PRINT_MINOR_VERSION@"
#define _DLT_PACKAGE_PATCH_LEVEL "@PRINT_PATCH_LEVEL@"
#define _DLT_PACKAGE_REVISION "@PRINT_REVISION@"

#endif
