/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#ifndef __VERSION_H_
#define __VERSION_H_

#define PACKAGE_VERSION_STATE "@PRINT_VERSION_STATE@"
#define PACKAGE_VERSION "@PRINT_VERSION@"
#define PACKAGE_MAJOR_VERSION "@PRINT_MAJOR_VERSION@"
#define PACKAGE_MINOR_VERSION "@PRINT_MINOR_VERSION@"
#define PACKAGE_PATCH_LEVEL "@PRINT_PATCH_LEVEL@"
#define PACKAGE_REVISION "@PRINT_REVISION@"

#endif
