/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#ifndef __DLT_VERSION_H_
#define __DLT_VERSION_H_

#define _DLT_PACKAGE_VERSION_STATE ""
#define _DLT_PACKAGE_VERSION "2.4.2"
#define _DLT_PACKAGE_MAJOR_VERSION "2"
#define _DLT_PACKAGE_MINOR_VERSION "4"
#define _DLT_PACKAGE_PATCH_LEVEL "2"
#define _DLT_PACKAGE_REVISION "v2.4.2_8_gf44294b"

#endif
