/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#ifndef __DLT_VERSION_H_
#define __DLT_VERSION_H_

#define _DLT_PACKAGE_VERSION_STATE "BETA"
#define _DLT_PACKAGE_VERSION "2.5.0"
#define _DLT_PACKAGE_MAJOR_VERSION "2"
#define _DLT_PACKAGE_MINOR_VERSION "5"
#define _DLT_PACKAGE_PATCH_LEVEL "0"
#define _DLT_PACKAGE_REVISION "v2.5.0_BETA_3_g5f0abf6"

#endif
