language: c

dist: xenial

compiler: gcc

script:
  - cmake -DWITH_DLT_TESTS=ON -DWITH_TESTSCRIPTS=ON -DWITH_DLT_UNIT_TESTS=ON -DWITH_SYSTEMD=ON -DWITH_SYSTEMD_JOURNAL=ON CMakeLists.txt
  - make
  - sudo make install
  - ./.travis/gtest_dlt_all.sh
  - ./src/tests/dlt-test-user

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libdbus-1-dev
      - build-essential
      - systemd
      - libsystemd-dev
