language: c

compiler: gcc

script: cmake -DWITH_DLTTEST=on -DWITH_TEST_SCRIPTS=on -DWITH_DLT_UNIT_TEST=on CMakeLists.txt && make && ./src/tests/dlt-test-user

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libdbus-1-dev
      - build-essential