.TH dlt-system 1   "April 13, 2012" "version 2.9.0" "USER COMMANDS"
.SH NAME
dlt-system \- DLT system logging process
.SH SYNOPSIS
.B dlt-system
[\-h] [\-c filename]
.SH DESCRIPTION
The DLT system logging process is the central application, which logs
system information from the platform. It provides the features
filetransfer, syslog adapater, logging of any kind of files and
procfilesystem logger. The individual features can be enabled and
disabled in the configuration file. 
.PP
dlt-system loads by default the configuration file /etc/dlt-system.conf. 
See dlt-system.conf(1).
.SH OPTIONS
.TP
\-h
Display a short help text.
.TP
\-c
Load an alternative configuration file. By default the configuration
file /etc/dlt.conf is loaded.
.SH EXAMPLES
.TP
Start DLT system with own configuration:
.B dlt-system
\-c ~/my-configuration.cfg \-v
.PP
.SH EXIT STATUS
Non zero is returned in case of failure.
.SH AUTHOR
Alexander Wenzel (alexander.aw.wenzel (at) bmw.de)
.SH SEE ALSO
dlt-system.conf(5)
dlt-daemon(1)

