.TH dlt-receive 1  "October 31, 2011" "version 2.4.0" "USER COMMANDS"
.SH NAME
dlt-receive \- Console based client for DLT Logging
.SH SYNOPSIS
.B dlt-receive
[\-h] [\-a] [\-x] [\-m] [\-s][\-o filename] [\-v] [\-y]
[\-b baudrate] [\-e ecuid]hostname/serial_device_name
.SH DESCRIPTION
Receive DLT messages from DLT daemon and print or store the messages.
.SH OPTIONS
.TP
\-h
Display a short help text.
.TP
\-a
Print DLT file; payload as ASCII.
.TP
\-x
Print DLT file; payload as hex.
.TP
\-m
Print DLT file; payload as hex and ASCII.
.TP
\-s
Print DLT file; only headers.
.TP
\-o
Output messages in new DLT file.
.TP
\-v
Verbose mode.
.TP
\-y
Serial device mode.
.TP
\-b
Serial device baudrate (Default: 115200).
.TP
\-e
Set ECU ID (Default: RECV).
.SH EXAMPLES
.TP
Convert DLT file into ASCII:
.B dlt-convert
\-a mylog.dlt
.PP
.TP
Join two log files:
.B dlt-convert
\-o newlog.dlt mylog1.dlt mylog2.dlt
.PP
.SH EXIT STATUS
Non zero is returned in case of failure.
.SH AUTHOR
Alexander Wenzel (alexander.aw.wenzel (at) bmw.de)
.SH SEE ALSO
dlt-daemon(1)
