'\" t
.\"     Title: dlt-convert
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/12/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DLT\-CONVERT" "1" "05/12/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dlt-convert \- Convert DLT Logging files into ASCII
.SH "SYNOPSIS"
.sp
\fBdlt\-convert\fR [\-h] [\-a] [\-x] [\-m] [\-s][\-o filename] [\-v] [\-c] [\-b number] [\-e number] [\-w] file1 [file2] [file3]
.SH "DESCRIPTION"
.sp
Read DLT files, print DLT messages as ASCII and store the messages again\&. Use Ranges and Output file to cut DLT files\&. Use two files and Output file to join DLT files\&.
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Display a short help text\&.
.RE
.PP
\fB\-a\fR
.RS 4
Print DLT file; payload as ASCII\&.
.RE
.PP
\fB\-x\fR
.RS 4
Print DLT file; payload as hex\&.
.RE
.PP
\fB\-m\fR
.RS 4
Print DLT file; payload as hex and ASCII\&.
.RE
.PP
\fB\-s\fR
.RS 4
Print DLT file; only headers\&.
.RE
.PP
\fB\-o\fR
.RS 4
Output messages in new DLT file\&.
.RE
.PP
\fB\-v\fR
.RS 4
Verbose mode\&.
.RE
.PP
\fB\-c\fR
.RS 4
Count number of messages\&.
.RE
.PP
\fB\-b\fR
.RS 4
First messages to be handled\&.
.RE
.PP
\fB\-e\fR
.RS 4
Last message to be handled\&.
.RE
.PP
\fB\-w\fR
.RS 4
Follow dlt file while file is increasing\&.
.RE
.SH "EXAMPLES"
.PP
Start DLT daemon in background mode
.RS 4
\fBdlt\-daemon \-d\fR
.RE
.PP
Start DLT daemon with own configuration
.RS 4
\fBdlt\-daemon \-c ~/my\-dlt\-configuration\&.cfg\fR
.RE
.PP
Convert DLT file into ASCII
.RS 4
\fBdlt\-convert \-a mylog\&.dlt\fR
.RE
.PP
Cut a specific range, e\&.g\&. from message 1 to message 3 from a file called log\&.dlt and store the result to a file called newlog\&.dlt
.RS 4
\fBdlt\-convert \-b 1 \-e 3 \-o newlog\&.dlt log\&.dlt\fR
.RE
.PP
Paste two dlt files log1\&.dlt and log2\&.dlt to a new file called newlog\&.dlt
.RS 4
\fBdlt\-convert \-o newlog\&.dlt log1\&.dlt log2\&.dlt\fR
.RE
.SH "EXIT STATUS"
.sp
Non zero is returned in case of failure\&.
.SH "AUTHOR"
.sp
Alexander Wenzel (alexander\&.aw\&.wenzel (at) bmw\&.de)
.SH "COPYRIGHT"
.sp
Copyright \(co 2015 BMW AG\&. License MPL\-2\&.0: Mozilla Public License version 2\&.0 http://mozilla\&.org/MPL/2\&.0/\&.
.SH "RESOURCES"
.sp
Main web site: http://projects\&.genivi\&.org/diagnostic\-log\-trace Mailinglist: https://lists\&.genivi\&.org/mailman/listinfo/genivi\-diagnostic\-log\-and\-trace
.SH "SEE ALSO"
.sp
dlt\-daemon(1)
