'\" t
.\"     Title: dlt.conf
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 02/23/2016
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DLT\&.CONF" "5" "02/23/2016" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dlt.conf \- DLT daemon configuration file
.SH "DESCRIPTION"
.sp
The DLT daemon is the central application which gathers logs and traces from different applications, stores them temporarily or permanently and transfers them to a DLT client application, which could run directly on the GENIVI system or more likely on some external tester device\&.
.sp
The configuration file dlt\&.conf allows to configure the different runtime behaviour of the dlt\-daemon\&. It is loaded during startup of dlt\-daemon\&.
.sp
By default dlt\-daemon loads the file /etc/dlt\&.conf\&. An alternative configuration file can be loaded with the option \-c\&.
.SH "GENERAL OPTIONS"
.PP
\fBDaemonize\fR
.RS 4
If set to 1 DLT daemon is started in background as daemon\&. This option is only needed in System V init systems\&. In systemd based startup systems the daemon is started by spawning own process\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBSendSerialHeader\fR
.RS 4
If set to 1 DLT daemon sends each DLT message to the client with prepanding the serial header "DLS0x01"\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBSendContextRegistration\fR
.RS 4
If set to 1 each context which is registered from an application in the DLT daemon generates a message to inform the DLT client about the new context\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBSendMessageTime\fR
.RS 4
If set to 1 DLt daemon sends each second a DLT control message to the client with the current timestamp from the system\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBECUId\fR
.RS 4
This value sets the ECU Id, which is sent with each DLT message\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: ECU1
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBGatewayMode\fR
.RS 4
If set to 1 gateway mode is enabled which means this ECU serves as gateway to forward messages from others\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBSharedMemorySize\fR
.RS 4
This value sets the size of the shared memory, which is used to exchange DLT messages between applications and daemon\&. This value is defined in bytes\&. If this value is changed the system must be rebooted to take effect\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 100000
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBPersistanceStoragePath\fR
.RS 4
This is the directory path, where the DLT daemon stores its runtime configuration\&. Runtime configuration includes stored log levels, trace status and changed logging mode\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: /tmp
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBLoggingMode\fR
.RS 4
The logging console for internal logging of dlt\-daemon\&.

0 = log to stdout, 1 = log to syslog, 2 = log to file (see LoggingFilename)
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBLoggingLevel\fR
.RS 4
The internal log level, up to which logs are written\&.

LOG_EMERG = 0, LOG_ALERT = 1, LOG_CRIT = 2, LOG_ERR = 3, LOG_WARNING = 4, LOG_NOTICE = 5, LOG_INFO = 6, LOG_DEBUG = 7
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 6
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBLoggingFilename\fR
.RS 4
If LoggingMode is set to 2 logs are written to the file path given here\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: /tmp/dlt\&.log
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBTimeOutOnSend\fR
.RS 4
Socket timeout in seconds for sending to clients\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 4
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBRingbufferMinSize\fR
.RS 4
The minimum size of the Ringbuffer, used for storing temporary DLT messages, until client is connected\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 500000
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBRingbufferMaxSize\fR
.RS 4
The max size of the Ringbuffer, used for storing temporary DLT messages, until client is connected\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 10000000
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBRingbufferStepSize\fR
.RS 4
The step size the Ringbuffer is increased, used for storing temporary DLT messages, until client is connected\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 500000
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBContextLogLevel\fR
.RS 4
Initial log\-level that is sent when an application registers\&.

DLT_LOG_OFF = 0, DLT_LOG_FATAL = 1, DLT_LOG_ERROR = 2, DLT_LOG_WARN = 3, DLT_LOG_INFO = 4, DLT_LOG_DEBUG = 5, DLT_LOG_VERBOSE = 6
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 4
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBContextTraceStatus\fR
.RS 4
Initial trace\-status that is sent when an application registers\&.

DLT_TRACE_STATUS_OFF = 0, DLT_TRACE_STATUS_ON = 1
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBForceContextLogLevelAndTraceStatus\fR
.RS 4
Force log level and trace status of context to not exceed "ContextLogLevel" and "ContextTraceStatus"\&.

If set to 1 (ON) whenever a context registers or changes the log\-level it has to be lower or equal to ContextLogLevel\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.SH "CONTROL APPLICATION OPTIONS"
.PP
\fBControlSocketPath\fR
.RS 4
Path to control socket\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: /tmp/dlt\-ctrl\&.sock
.fi
.if n \{\
.RE
.\}
.RE
.SH "OFFLINE TRACE OPTIONS"
.PP
\fBOfflineTraceDirectory\fR
.RS 4
If this option is set, offline trace is enabled\&. This value sets the directory path to the offline trace memory\&. The directory must already exist\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: Offline tracing is disabled\&.
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineTraceFileSize\fR
.RS 4
This value defines the max size of a offline trace file, if offline trace is enabled\&. This value is defined in bytes\&. If the files size of the current used log file is exceeded, a new log file is created\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 1000000
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineTraceMaxSize\fR
.RS 4
This value defines the max offline Trace memory size, if offline trace is enabled\&. This value is defined in bytes\&. If the overall offline trace size is excedded, the oldest log files are deleted, until a new trace file fits the overall offline trace max size\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 4000000
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineTraceFileNameTimestampBased\fR
.RS 4
Filename timestamp based or index based\&.

1 = timestamp based, 0 = index based
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 1
.fi
.if n \{\
.RE
.\}
.RE
.SH "LOCAL CONSOLE OUTPUT OPTIONS"
.PP
\fBPrintASCII\fR
.RS 4
Prints each received DLT message from the application in ASCII to the local console\&. This option should only be anabled for debugging purpose\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: Function is disabled
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBPrintHex\fR
.RS 4
Prints each received DLT message from the application in ASCII to the local console\&. The payload is printed in Hex\&. This option should only be anabled for debugging purpose\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: Function is disabled
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBPrintHeadersOnly\fR
.RS 4
Prints each received DLT message from the application in ASCII to the local console\&. Only the header is printed\&. This option should only be anabled for debugging purpose\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: Function is disabled
.fi
.if n \{\
.RE
.\}
.RE
.SH "SERIAL CLIENT OPTIONS"
.PP
\fBRS232DeviceName\fR
.RS 4
If this value is set to a serial device name, e\&.g\&. /dev/ttyS0, a serial port is used for logging to a client\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: Serial port for logging is disabled
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBRS232Baudrate\fR
.RS 4
The used serial baud rate, if serial loggin is enabled\&. The RS232DeviceName must be set to enable serial logging\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 115200
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBRS232SyncSerialHeader\fR
.RS 4
If serial logging is enabled, each received DLT message is checked to contain a serial header\&. If the DLT message contains no serial header, the message is ignored\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: Function is disabled
.fi
.if n \{\
.RE
.\}
.RE
.SH "TCP CLIENT OPTIONS"
.PP
\fBTCPSyncSerialHeader\fR
.RS 4
Each received DLT message on a TCP connection is checked to contain a serial header\&. If the DLT message contains no serial header, the message is ignored\&.
.RE
.SH "ECU SOFTWARE VERSION OPTIONS"
.PP
\fBSendECUSoftwareVersion\fR
.RS 4
Periodically send ECU version info\&.

0 = disabled, 1 = enabled
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBPathToECUSoftwareVersion\fR
.RS 4
Absolute path to file storing version information \- if disabled the DLT version will be send\&.
.RE
.SH "TIMEZONE INFO OPTIONS"
.PP
\fBSendTimezone\fR
.RS 4
Periodically send timezone info\&. 0 = disabled, 1 = enabled
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0
.fi
.if n \{\
.RE
.\}
.RE
.SH "OFFLINE LOGSTORAGE OPTIONS"
.PP
\fBOfflineLogstorageMaxDevices\fR
.RS 4
Maximum devices to be used as offline logstorage devices\&.

0 = disabled, 1 \&.\&. DLT_OFFLINE_LOGSTORAGE_MAX_DEVICES
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 0 (Functionality is disabled)
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineLogstorageDirPath\fR
.RS 4
Path to store DLT offline log storage messages\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: off
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineLogstorageTimestamp\fR
.RS 4
Appends timestamp in log file name\&.

0 = disabled, 1 = enabled
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 1
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineLogstorageDelimiter\fR
.RS 4
Appends delimiter in log file name, only punctuation characters allowed\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: _
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineLogstorageMaxCounter\fR
.RS 4
Wrap around value for log file count in file name\&.

.sp
.if n \{\
.RS 4
.\}
.nf
Default: UINT_MAX
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBOfflineLogstorageCacheSize\fR
.RS 4
Maximal used memory for Logstorage Cache in KB\&.
.sp
.if n \{\
.RS 4
.\}
.nf
Default: 30000 KB
.fi
.if n \{\
.RE
.\}
.RE
.SH "AUTHOR"
.sp
Alexander Wenzel (alexander\&.aw\&.wenzel (at) bmw\&.de)
.SH "RESOURCES"
.sp
Main web site: http://projects\&.genivi\&.org/diagnostic\-log\-trace Mailinglist: https://lists\&.genivi\&.org/mailman/listinfo/genivi\-diagnostic\-log\-and\-trace
.SH "SEE ALSO"
.sp
dlt\-daemon(1), dlt\-system(1)
