/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#ifndef __DLT_VERSION_H_
#define __DLT_VERSION_H_

#define _DLT_PACKAGE_VERSION_STATE "@DLT_VERSION_STATE@"
#define _DLT_PACKAGE_VERSION "@DLT_VERSION@"
#define _DLT_PACKAGE_MAJOR_VERSION "@DLT_MAJOR_VERSION@"
#define _DLT_PACKAGE_MINOR_VERSION "@DLT_MINOR_VERSION@"
#define _DLT_PACKAGE_PATCH_LEVEL "@DLT_PATCH_LEVEL@"
#define _DLT_PACKAGE_REVISION "@DLT_REVISION@"

#ifdef DLT_SYSTEMD_ENABLE
#define _DLT_SYSTEMD_ENABLE "+SYSTEMD"
#else
#define _DLT_SYSTEMD_ENABLE "-SYSTEMD"
#endif

#ifdef DLT_SYSTEMD_WATCHDOG_ENABLE
#define _DLT_SYSTEMD_WATCHDOG_ENABLE "+SYSTEMD_WATCHDOG"
#else
#define _DLT_SYSTEMD_WATCHDOG_ENABLE "-SYSTEMD_WATCHDOG"
#endif

#ifdef DLT_TEST_ENABLE
#define _DLT_TEST_ENABLE "+TEST"
#else
#define _DLT_TEST_ENABLE "-TEST"
#endif

#ifdef DLT_SHM_ENABLE
#define _DLT_SHM_ENABLE "+SHM"
#else
#define _DLT_SHM_ENABLE "-SHM"
#endif

#endif
