/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#ifndef __DLT_VERSION_H_
#define __DLT_VERSION_H_

#define _DLT_PACKAGE_VERSION_STATE "@DLT_VERSION_STATE@"
#define _DLT_PACKAGE_VERSION "@DLT_VERSION@"
#define _DLT_PACKAGE_MAJOR_VERSION "@DLT_MAJOR_VERSION@"
#define _DLT_PACKAGE_MINOR_VERSION "@DLT_MINOR_VERSION@"
#define _DLT_PACKAGE_PATCH_LEVEL "@DLT_PATCH_LEVEL@"
#define _DLT_PACKAGE_REVISION "@DLT_REVISION@"

#endif
